### ISSUE TITLE
SPI support SDIO half-duplex

### ISSUE THREAD

**Issue by warriorfenixSM** [arduino/ArduinoCore-avr#104]
Hi!

I need your help to know if the library support 3-wire SPI and if yes. How?

I attacht the picture.

![image](https://user-images.githubusercontent.com/30696031/64736369-c1c72380-d4ea-11e9-9487-9b13eca0cd10.png)

I need to control a Optical track Sensor.

[PAT9130EW - AN04 SPI ControlFlow V0.1.pdf](https://github.com/arduino/ArduinoCore-avr/files/3602784/PAT9130EW.-.AN04.SPI.ControlFlow.V0.1.pdf)
[PAT9130EW-TKMT_GDS-R1.0_12062017_21006AEN.pdf](https://github.com/arduino/ArduinoCore-avr/files/3602785/PAT9130EW-TKMT_GDS-R1.0_12062017_21006AEN.pdf)

**Comment by warriorfenixSM** [comment]
Hi i try to use SPI.begin transaction but not works

![image](https://user-images.githubusercontent.com/30696031/64896076-d0464400-d67e-11e9-8b15-d521ff4904cf.png)

**Comment by cmaglie** [comment]
Please move the discussion to the arduino forum:

forum.arduino.cc

you will surely find more help over there.
