### ISSUE TITLE
Arduino AVR Boards post 1.6.11 bloats build - consumes memory

### ISSUE THREAD

**Issue by Larry-M** [arduino/ArduinoCore-avr#137]
Reference https://discuss.inventables.com/t/inventables-fork-of-grbl-too-large-32-266-bytes-when-compiled/28148/4

**Comment by cmaglie** [comment]
By looking at the linked thread the problem seems fixed, so I'm going forward and closing this as fixed.

If the problem is still present today, please re-test with a recent IDE, since 1.6.11 is quite old now, and re-open the issue.
