### ISSUE TITLE
power_usart3_enable() and power_usart3_disable() missing from power.h

### ISSUE THREAD

**Issue by pippo-75** [arduino/ArduinoCore-avr#139]
Hi all, I report a bug(?) in power.h library, distributed with IDE 1.6.10 Win.
The error is:
exit status 1
'Power_usart3_disable' was not declared in this scope
![ide1 6 10_usart3](https://cloud.githubusercontent.com/assets/4587356/17935375/6ad71b8a-6a1b-11e6-953c-1f9878d7b166.png)

The library lacks the definition for USART3. Solved by adding the following lines (from 852 to 855):
```c
# if defined (__ AVR_HAVE_PRR1_PRUSART3)
# define power_usart3_enable () (PRR1 & = (uint8_t) ~ (1 << PRUSART3))
# define power_usart3_disable () (PRR1 | = (uint8_t) (1 << PRUSART3))
# endif
```

A problem with the Wire library (Note: the IDE 1.6.9 compiled all, without errors):
To make sure that the IDE 1.6.10 correctly loads the LiquidCrystal_I2C library,
I had to move the content of the `src` folder to the root (Wire folder). 

Now compile fine.

**Comment by facchinm** [comment]
Latest toolchain for avr contains the fix in avr-libc
