### ISSUE TITLE
Boards manager install of older avr-gcc breaks compilation for all AVR boards in 1.6.10.

### ISSUE THREAD

**Issue by damellis** [arduino/ArduinoCore-avr#142]
A user of the attiny boards package encountered this: https://github.com/damellis/attiny/issues/105

The previous ATtiny package json (https://raw.githubusercontent.com/damellis/attiny/f026e80bc8fa4e33714bfe28ceafdd8829d85293/package_damellis_attiny_index.json) included explicit dependencies on the avr-gcc and avrdude versions that came with Arduino 1.6.9 (and previous). With 1.6.10, newer versions of these tools are included, so installing the ATtiny package also installed these older tools. These older tools then get used for all AVR boards.

It appears the older tools don't support LTO or plugins, so compiling in 1.6.10 gives the error:

```
sorry - this program has been built without plugin support
exit status 1
```

I think I fixed this for the ATtiny package by removing the explicit tool dependency, and assuming that avr-gcc and avrdude will be included with the Arduino IDE. 

This may remain a problem for other third-party hardware packages, though. Maybe the IDE should use the bundled avr-gcc and avrdude for bundled boards even if another version has been installed for other boards? Maybe only if the newly-installed version is older than the bundled version?

**Comment by facchinm** [comment]
New IDEs use the json definitions to select the right toolchain if no version is specified in `platform.txt`, thus closing as fixed
