### ISSUE TITLE
Leonardo requests too much USB current

### ISSUE THREAD

**Issue by HelenFoster** [arduino/ArduinoCore-avr#147]
ATmega32u4 boards claim to require 500mA with no fallback. This value is set in USBCore.h and reprogrammed each time a sketch is uploaded. The result is that the serial and HID connections fail on a 100mA USB port even though the board actually uses far less than 100mA.

It could be argued that the user circuit might use up to 500mA. However, the Leonardo bootloader and the Uno r3 only request 100mA (fortunately, since it would be much more difficult to change). Also, the board itself, and any user circuitry powered directly from the 5V line, still try to draw current even if the requested USB configuration is denied.

Possibilities I have thought of (not knowing if the latter two are practical):
- Change to 100mA to match the bootloader and Uno r3;
- Let the sketch set the USB current requirement;
- Request 500mA and fall back to 100mA, with some way for the sketch to check what happened so it can avoid powering up external circuitry (might also be worth considering for other boards).

**Comment by lxrobotics** [comment]
@xulioc I'd consider the change of USB power very much an advanced feature. If you create a PR demonstrating a user-friendly way to change `USB_CONFIG_POWER_MA` we will consider integrating it.
