### ISSUE TITLE
some definition changes to save some bytes

### ISSUE THREAD

**Issue by night-ghost** [arduino/ArduinoCore-avr#153]
-int analogRead(uint8_t pin)
+unsigned int analogRead(uint8_t pin)

because it's really unsigned

-void attachInterrupt(uint8_t interruptNum, void (_userFunc)(void), int mode) {
+void attachInterrupt(uint8_t interruptNum, void (_userFunc)(void), uint8_t mode) {

because mode has only low values

-int digitalRead(uint8_t pin)
+uint8_t digitalRead(uint8_t pin)

because it returns only 0 or 1

**Comment by lxrobotics** [comment]
@night-ghost a similiar proposition was made in https://github.com/arduino/Arduino/pull/4625 and refused based on the argument of breaking the Arduino API signator (see  https://github.com/arduino/Arduino/pull/4625#issuecomment-191856110 ) therefore I am closing this issue.
