### ISSUE TITLE
src dirs in libraries

### ISSUE THREAD

**Issue by ktrace** [arduino/ArduinoCore-avr#16]
ArduinoCore-avr/libraries/{Wire, ...}/  has subdir src, but original Arduino 1.6.7 has no. Is it ok? Maybe need rearrange and move *.h/*.c level up?

https://github.com/ladislas/Bare-Arduino-Project/issues/51

**Comment by wmarkow** [comment]
It looks that this is defined in a [Arduino-IDE-1.5:-Library-specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification). According to this, sources should be inside of **src** folder.

**Comment by lxrobotics** [comment]
@wmarkow is completely right pointing to the [Arduino-IDE-1.5:-Library-specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) :+1:
