### ISSUE TITLE
#include "twi.h" needs to be surrounded by extern "C" { [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/ArduinoCore-avr#214]
This is [Issue 791](http://code.google.com/p/arduino/issues/detail?id=791) moved from a Google Code project.
Added by 2012-01-14T23:37:51.000Z by [jan.Baey...@gmail.com](http://code.google.com/u/112096662257859578748/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

This is a code improvement request for the file twi.h.
When including twi.h in a cpp file it needs to be surrounded by extern "C" otherwise name mingling problems occur.
It would be better if twi.h used
```c++
#ifdef __cplusplus

extern "C" {
#endif
```
**Why?**
Developers start being confused and start using extern "C" for files that do not need it which may lead to lost time.
For instance wire.cpp contains:
```c++
extern "C" {
  #include <stdlib.h>
  #include <string.h>
  #include <inttypes.h>
  #include "twi.h"
}
```
only twi.h needs the `extern "C"`

Would this cause any incompatibilities with previous versions? 
This will not cause any incompatibilities. I attached the modified twi.h which I tested in my environment.

**Comment by lxrobotics** [comment]
This has been implemented ( https://github.com/arduino/ArduinoCore-avr/blob/master/libraries/Wire/src/Wire.cpp#L23:L28 ).
