### ISSUE TITLE
Upgrade avr-gcc to newer version that's 64-bit for macs

### ISSUE THREAD

**Issue by SConaway** [arduino/ArduinoCore-avr#22]
Upgrade avr-gcc to newer version that's 64-bit for macs. I'm not sure how to change tools so some pointers would help.

Thanks

**Comment by SConaway** [comment]
I just swithced out the files on my mac and it seems to work.

**Comment by matthijskooijman** [comment]
I suspect this is something to report at https://github.com/arduino/toolchain-avr ?

**Comment by SConaway** [comment]
Yes.
