### ISSUE TITLE
"PE" Redifined error with ATmega8 and gcc 4.5.3 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/ArduinoCore-avr#226]
This is [Issue 618](http://code.google.com/p/arduino/issues/detail?id=618) moved from a Google Code project.
Added by 2011-09-01T13:50:50.000Z by [arkali...@gmail.com](http://code.google.com/u/112346604237000176453/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

**What steps will reproduce the problem?**

Building with gcc 4.5.3 for ATmega8 the "PE" is redefined in pins_arduino.c line 72. The previous declaration is in file iom8.h in line 516, is the PE bit of UCSRA. With ATmega328 where is no problem as the PE bit is renamed.
An easy solution is to move PE, PF, PG, PH, PJ, PK, and PL definitions from lines 72-78 in pins_arduino.c to line 82, inside the ATmega1280 block, as these ports exist only in arduino mega boads.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

I am using 1.0beta2 with arduino-uno under debian-linux.

**Please provide any additional information below.**

**Comment by facchinm** [comment]
Keeping track on #148
