### ISSUE TITLE
Improved delayMicroseconds(). [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/ArduinoCore-avr#235]
This is [Issue 256](http://code.google.com/p/arduino/issues/detail?id=256) moved from a Google Code project.
Added by 2010-05-11T15:28:29.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core, OpSys-All
### Original description

**What change would like to see?**

Switching to delayMicroseconds() code here: http://www.arduino.cc/cgi-bin/yabb2/YaBB.pl?num=1273573826

**Why?**

Making the function more accurate for compile-time-constant delays and generalizing it for any 
CPU speed.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

There could be some issues with very timing sensitive routines.

**Comment by matthijskooijman** [comment]
This is mostly a duplicate of #118 (though this also suggests generalizing to any frequency, but I'm planning to include that in a fix for #118 as well).
