### ISSUE TITLE
avrdude doesn't properly write long series of 0xFF [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/ArduinoCore-avr#236]
This is [Issue 273](http://code.google.com/p/arduino/issues/detail?id=273) moved from a Google Code project.
Added by 2010-06-07T03:48:36.000Z by [adamww...@gmail.com](http://code.google.com/u/101494205604337491076/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

**What steps will reproduce the problem?**
1. Make an array of at least a page of 0xFF in progmem.
2. Try to read it from inside your Arduino sketch.
3. Notice!  The page will contain whatever the memory contents were the
last time you programmed the chip!

**What is the expected output? What do you see instead?**
I expect to see a big long series of 0xff, and instead, I see whatever was
on the chip before.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
I am using Arduino-0018 on Ubuntu, with a variety of Arduino boards.

**Please provide any additional information below.**

I first noticed this a few days ago:
http://forum.arduino.cc/index.php?topic=8814.msg72667#msg72667

I reported this upstream:
https://savannah.nongnu.org/bugs/?30061
but I noticed that there is a version of avrdude
in the arduino tree, so I figured I'd report it here as well.

I dug around the source, and I narrowed the issue down to
stk500_paged_write in stk500.c, there's a check for stk500_is_page_empty.
If the whole page consists of 0xFF, the page isn't written.  This assumes
the page/chip has been erased. Autoerase is turned off in arduino, so this
is an incorrect assumption.

~~I commented out~~

~~/\* Only skip on empty page if programming flash. */~~
~~if (flash) {~~
~~if (stk500_is_page_empty(addr, block_size, m->buf)) {~~
~~continue;~~
~~}~~
~~} ~~

~~in stk500.c, and this fixes the issue, increasing accuracy at the expense
of write speed.~~

---
EDIT:
Update: Commenting that section out doesn't actually appear to fix it. Sorry, errant test result on my side.

However, commenting out the line
```java
commandDownloader.add("-D"); // don't erase
```
in app/src/processing/app/debug/AvrdudeUploader.java does fix this issue.

---
I'm not sure of how it usually works, if you usually wait for upstream to
fix, or whatnot, but I thought I'd let you know.  Thanks!

**Comment by facchinm** [comment]
Should be fixed by avrdude 6.3, please reopen if not
