### ISSUE TITLE
TwoWire::flush(void) to flush rxBuffer missing

### ISSUE THREAD

**Issue by RobTillaart** [arduino/ArduinoCore-avr#253]
Missing in Wire lib is the flush() which can be quite straightforward. 

``` C++
void TwoWire::flush(void)
{
  rxBufferIndex = 0;
  rxBufferLength = 0;
}
```

maybe it should be called rxFlush() to allow a txFlush() in the future.

This allows one to flush the receive buffer e.g. after reading first byte which indicates the type of the answer.

``` C++
if (Wire.Read() != 5)
{
  Wire.flush();
}
else processBuffer();
```

**Comment by sandeepmistry** [comment]
I'm marking this as won't fix, flush() is intended for TX only and is not needed in the Wire lib.
