### ISSUE TITLE
Allow redefinition of delay()

### ISSUE THREAD

**Issue by mikaelpatel** [arduino/ArduinoCore-avr#275]
Could delay() be made a weak definition so that it could be redefined as yield()? This would allow adaptations such as dropping into low-power mode in a Scheduler when all tasks are in delay(). 

Cheers!

**Comment by lxrobotics** [comment]
Hi @mikaelpatel :wave: After discussing this topic internally we've come to the conclusion to not define `delay` as a `weak` function right now. The major concern is that it's very easy for users to unwittingly overwrite this function which is pretty much used everywhere. However, in the future `delay` might be modified to accomodate such functionality as the low-power sleep mentioned by you.
