### ISSUE TITLE
[Proposal] Provide for hook into Timer0 overflow ISR

### ISSUE THREAD

**Issue by gbhug5a** [arduino/ArduinoCore-avr#276]
It would be useful if there was a way to add additional operations or functions to the existing timer0 ISR.  Using  some other timer interrupt might conflict with normal functions, such as analog writes.  But simply adding code to the existing ISR conflicts with nothing.  The 1 ms rate, or a multiple of it, would be perfect for polling functions, such as servicing a rotary encoder or momentary switches, or display refreshes, in a way that wouldn't be compromised by delay() or other loop() operations.  Perhaps the existing ISR could call or jump to a specifically named function, if it exists.  Or if there was a way to replace the interrupt vector with mine, I could write a new ISR which includes the standard millis update code in addition to my other functions.

**Comment by lxrobotics** [comment]
Closing this issue since we will not add timer hooks for now.
