### ISSUE TITLE
Missing GPG signature

### ISSUE THREAD

**Issue by NicoHood** [arduino/ArduinoCore-avr#310]
Hi, the signature for the current release is missing. I expect it here:
https://downloads.arduino.cc/cores/avr-1.8.2.tar.bz2.asc

**Comment by cmaglie** [comment]
added signature.

**Comment by NicoHood** [comment]
https://downloads.arduino.cc/cores/avr-1.8.3.tar.bz2.asc
Is missing again

**Comment by cmaglie** [comment]
added signature.

**Comment by NicoHood** [comment]
There is no signature available under the link above.

**Comment by cmaglie** [comment]
sorry, updated the link...
