### ISSUE TITLE
USB_SendStringDescriptor may be extern

### ISSUE THREAD

**Issue by sylvainpelissier** [arduino/ArduinoCore-avr#35]
The function **USB_SendStringDescriptor** may be reused to write PluggableUSB Module. For example, in an Interface Descriptor, the Interface field _iInterface_ is an index of String Descriptor describing this interface. In order to have it available outside, it has to be not static and declared in USBAPI.h.

**Comment by lxrobotics** [comment]
Hi @sylvainpelissier :wave: Thank you very much for pointing this out :+1: Since we are currently understaffed it would be fantastic if you could provide a PR with the actual change in code. I'll be closing this issue and expecting your PR.
