### ISSUE TITLE
Wire.lastError Not defined in the Class

### ISSUE THREAD

**Issue by FJRusso53** [arduino/ArduinoCore-avr#454]
@greyltc
I am using IDE V 1.8.19.  But had the same problem in V 2.0
On line 378 is the following Macro:
                                  X("Wire.lastError", WIRE_LAST_ERROR, PUSH Wire.lastError()) \
On compiling:   ESP32forth705:378:50: error: 'class TwoWire' has no member named 'lastError'
   X("Wire.lastError", WIRE_LAST_ERROR, PUSH Wire.lastError()) \

I commented out the line and it successfully compiled But on loading to my board,  ESP32 Dev Mod, it repeatedly reboots after trying to call the function.  
I also commented out line 1130 but that created other errors

[ESP32forth705.txt](https://github.com/arduino/ArduinoCore-avr/files/7987370/ESP32forth705.txt)
.

**Comment by per1234** [comment]
Hi @FJRusso53. Thanks for taking the time to submit an issue.

Wire is a ["platform bundled library"](https://arduino.github.io/arduino-cli/latest/platform-specification/#platform-bundled-libraries). This means that each boards platform provides its own variant of the library. The Arduino build system picks the appropriate library automagically based on which board you are compiling for, and the APIs are fairly standardized, so the user is often not aware that a different library is used from one board to the next.

This repository contains the Wire library for the "Arduino AVR Boards" platform (e.g., Uno, Leonardo, Mega), and so we only track issues specific to this variant of the library here. The Wire library used when compiling for your "ESP32 Dev Mod" board is the one here:
https://github.com/espressif/arduino-esp32/blob/master/libraries/Wire

I recommend you to post about this error over on the Arduino Forum. I'm sure we'll be able to help you to get your sketch compiling over there:

https://forum.arduino.cc/
