### ISSUE TITLE
Arduino Uno Mini LE USB issue

### ISSUE THREAD

**Issue by parviznarimani** [arduino/ArduinoCore-avr#457]
Arduino USB driver doesn't have any certification file for Uno mini, and therefore some windows versions show this issue!!!
How should we resolve it!?
IDE: 1.8.19
Windows: 8.1
![image](https://user-images.githubusercontent.com/13968597/154157323-91936304-b536-4c24-b79d-40607323aff4.png)

**Comment by silvanocerza** [comment]
Fix has been released in core version [`1.8.5`](https://github.com/arduino/ArduinoCore-avr/releases/tag/1.8.5), closing this.

**Comment by silvanocerza** [comment]
My mistake, version `1.8.5` is not in production yet but only available in the staging index.
