### ISSUE TITLE
Which bootloader is atmega328p's ? 

### ISSUE THREAD

**Issue by Basilisvirus** [arduino/ArduinoCore-avr#469]
I am trying to find the bootloader for the atmega328p in the folder ArduinoCore-avr/bootloaders/atmega/.
1) All of the files say "168". Are all of these bootloaders for the atmega168?

2) for the atmega328 I see two   files. ATmegaBOOT_168_atmega328.hex and ATmegaBOOT_168_atmega328_pro_8MHz.hex. Which one of these are for the Atmega328p? (They might be for the Atmega328 and not for the Atmega328p?).

Thank you.

**Comment by per1234** [comment]
Hi @Basilisvirus. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/microcontrollers/59
