### ISSUE TITLE
Half duplex connection 

### ISSUE THREAD

**Issue by pierrotm777** [arduino/ArduinoCore-avr#517]
Hello,
I need to build a half duplex connection between my atmega2560 and a device ExpressLrs that use only one pin for Rx and Tx .
Does exist a solution?
Thanks for your help,
Pierre

**Comment by per1234** [comment]
Hi @pierrotm777. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

**Comment by pierrotm777** [comment]
Sorry
