### ISSUE TITLE
Create baseclass for HardwareSerial and SoftwareSerial

### ISSUE THREAD

**Issue by mark5438** [arduino/ArduinoCore-avr#538]
I know they both inherit stream. But stream can not be written to. Can I make an interface with write functions that they both inherit? Will have some pretty cool applications

**Comment by per1234** [comment]
@mark5438 it isn't clear to me what you are proposing. Please provide a detailed proposal.

Isn't this already done by the `Print` class, which the `Stream` class inherits?

https://github.com/arduino/ArduinoCore-API/blob/master/api/Print.h
