### ISSUE TITLE
Improving delay()

### ISSUE THREAD

**Issue by mikaelpatel** [arduino/ArduinoCore-avr#57]
The current implementation only calls yield() once (https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/wiring.c#L106)

```
void delay(unsigned long ms)
{
	uint32_t start = micros();

	while (ms > 0) {
		yield();
		while ( ms > 0 && (micros() - start) >= 1000) {
			ms--;
			start += 1000;
		}
	}
}
```
Could be improved to something like:
```
void delay(unsigned long ms)
{
	uint32_t start = micros();
	while ( ms > 0 && (micros() - start) >= 1000) {
		yield();
		ms--;
		start += 1000;
	}
}
```
Also adding the attribute "weak" could allow redefinition when needed, e.g. allow support for low power mode in Cooperative Scheduler, https://github.com/mikaelpatel/Arduino-Scheduler

`void delay(unsigned long ms) __attribute__ ((weak));
`

**Comment by cmaglie** [comment]
Looks like the "improved" version will never enter the while loop because `(micros() - start) >= 1000` can not be true?
