### ISSUE TITLE
Wrong maximum_size for optiBoot Nano

### ISSUE THREAD

**Issue by AlexGyver** [arduino/ArduinoCore-avr#98]
boards.txt line 145 (## Arduino Nano w/ ATmega328P) :
```
nano.menu.cpu.atmega328.upload.maximum_size=30720
```
should be 32256 for optiBoot v4
so the same for ATmega168 based boards - should be 15360
also fuses needs to be corrected too...

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/ArduinoCore-avr/issues/10

See the discussion there for an explanation of why it is that way.

**Comment by AlexGyver** [comment]
Ok! It is not good news(
